name: Compile and run

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  run:
    name: Run executable
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        max-candidates-per-token: [1000]
        edit-penalty-factor: [0.01]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download zipped corpus
        run: python scripts/download.py

      - name: Install Pipe Viewer
        run: sudo apt install pv -y

      - name: Compile executable
        run: scripts/build.sh

      - name: Run executable with piped corpus
        timeout-minutes: 330
        run: unzip -p data/corpus.zip corpus.txt | pv -B 128M | build/learn.exe --corpus -

      - name: Benchmark solution
        run: python src/main.py benchmark

      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.max-candidates-per-token }}-${{ matrix.edit-penalty-factor }}
          path: |
            data/frequency.txt
            data/screenshot.png
