name: Compile and run

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    name: Run executable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chromium
        run: sudo apt-get install chromium-chromedriver -y

      - name: Show path to Chromium
        run: whereis chromedriver

      - name: Download corpus
        run: python scripts/download.py

      - name: Compile executable
        run: scripts/build.sh
