name: Compile and run

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  run:
    name: Run executable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile executable
        run: scripts/build.sh
