name: Compile and run

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  run:
    name: Run executable
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        max-candidates-per-token: [200, 500, 800, 1000]
        edit-penalty-factor: [0.005, 0.01, 0.015, 0.02, 0.025, 0.03]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download zipped corpus
        run: python scripts/download.py

      - name: Install Pipe Viewer
        run: sudo apt install pv -y

      - name: Compile executable
        run: scripts/build.sh

      - name: Generate input file
        run: python scripts/input.py

      - name: Run executable with piped corpus
        timeout-minutes: 330
        run: |
          unzip -p data/corpus.zip corpus.txt | \
          pv -B 128M | \
          build/main.exe --corpus - --max-candidates-per-token ${{ matrix.max-candidates-per-token }} --edit-penalty-factor ${{ matrix.edit-penalty-factor }}

      - name: Benchmark solution
        run: python scripts/benchmark.py

      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.edit-penalty-factor }}
          path: |
            data/frequency.txt
            data/output.txt
            data/screenshot.png
